/**
 * Generated by Kerf from "/Users/samithmendis/Documents/Repos/kerf/examples/assets/chamfer-swatch.png" — do not edit by hand.
 * Regenerate: npx kerf trace "/Users/samithmendis/Documents/Repos/kerf/examples/assets/chamfer-swatch.png" --name ChamferSwatch
 * Clip mode uses an SVG <clipPath> (not CSS clip-path: polygon) because
 * this shape has curves, which polygon() can't express exactly. Needs React 18+ (useId).
 */
import * as React from "react";

const PATH_D =
  "M0.10071 0.10129L0 0.20258 0 0.60129 0 1 0.49879 0.99873 0.99758 0.99745 0.99914 0.69497C1 0.5286 0.99917 0.30417 0.99731 0.19624L0.99393 0 0.59767 0 0.20142 0 0.10071 0.10129";
const ASPECT_RATIO = 1.0049;

export interface ChamferSwatchProps extends Omit<React.SVGAttributes<SVGSVGElement>, "children"> {
  /** Uniform size (px or CSS length). Sets width and height together, preserving aspect ratio. Ignored if `height` is also set. */
  size?: number | string;
  width?: number | string;
  height?: number | string;
  /** Fill color when rendered as a flat shape (ignored when `children` is passed). */
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
  /** Pass children to clip arbitrary content (images, video, text) to this silhouette instead of filling it flat. */
  children?: React.ReactNode;
}

/**
 * ChamferSwatch — traced with Kerf.
 * No children: renders as a flat, filled/stroked SVG shape.
 * With children: clips whatever you pass in to this shape's silhouette.
 */
export function ChamferSwatch({
  size,
  width,
  height,
  fill = "currentColor",
  stroke = undefined,
  strokeWidth = 0,
  className,
  style,
  children,
  ...rest
}: ChamferSwatchProps) {
  const w = width ?? size;
  const h = height;
  const preserveAspect = h === undefined && w !== undefined ? ASPECT_RATIO : undefined;
  const clipId = React.useId();

  if (children) {
    return (
      <div
        className={className}
        data-kerf-shape="ChamferSwatch"
        style={{
          position: "relative",
          display: "inline-block",
          overflow: "hidden",
          width: w,
          height: h,
          aspectRatio: preserveAspect,
          clipPath: `url(#${clipId})`,
          WebkitClipPath: `url(#${clipId})`,
          ...style,
        }}
      >
        <svg width={0} height={0} style={{ position: "absolute" }} aria-hidden focusable="false">
          <defs>
            <clipPath id={clipId} clipPathUnits="objectBoundingBox">
              <path d={PATH_D} clipRule="evenodd" />
            </clipPath>
          </defs>
        </svg>
        {children}
      </div>
    );
  }

  return (
    <svg
      viewBox="0 0 1 1"
      preserveAspectRatio="none"
      width={w}
      height={h}
      className={className}
      data-kerf-shape="ChamferSwatch"
      style={{ aspectRatio: preserveAspect, ...style }}
      {...rest}
    >
      <path
        d={PATH_D}
        fill={fill}
        stroke={stroke}
        strokeWidth={strokeWidth}
        fillRule="evenodd"
        vectorEffect="non-scaling-stroke"
      />
    </svg>
  );
}

export default ChamferSwatch;
