import { pathToPolygonPercent } from "../trace/geometry.js";
import type { TraceResult } from "../trace/types.js";

export interface CodegenOptions {
  componentName: string;
  defaultFill?: string;
  defaultStroke?: string;
  defaultStrokeWidth?: number;
}

/**
 * Renders a fully self-contained TSX source string for the traced shape.
 * "Self-contained" is a deliberate design choice: the output has zero
 * runtime dependency on the `kerf` package. Once generated, the component
 * is exactly as much yours as any other file in your repo — copy it,
 * rename it, hand-edit the path, delete Kerf entirely. Nothing breaks.
 *
 * Clip mode (`children` passed) picks the simplest exact technique:
 *  - Straight-edged outline (chamfers, notches, bevels — Kerf's core case):
 *    a CSS `clip-path: polygon(...)` computed at generation time. Lossless,
 *    no hook, no ids, no hidden <svg>.
 *  - Curves or holes (which `polygon()` can't express exactly): an SVG
 *    `<clipPath>` with a `useId()` id. `useId` works in Server Components,
 *    so no `"use client"` is needed either way.
 */
export function generateComponentSource(result: TraceResult, opts: CodegenOptions): string {
  const {
    componentName,
    defaultFill = "currentColor",
    defaultStroke,
    defaultStrokeWidth = 0,
  } = opts;

  const strokeDefault = defaultStroke === undefined ? "undefined" : JSON.stringify(defaultStroke);
  // Only use a CSS polygon when the outline is already all straight lines —
  // approximating curves would trade exactness for nothing.
  const polygon = pathToPolygonPercent(result.pathD);
  const usesPolygon = polygon !== null;

  const fallbackReason =
    result.subpathCount > 1
      ? `this shape has ${result.subpathCount} subpaths (compound shape and/or holes)`
      : "this shape has curves";

  const headerNote = usesPolygon
    ? ""
    : ` * Clip mode uses an SVG <clipPath> (not CSS clip-path: polygon) because\n` +
      ` * ${fallbackReason}, which polygon() can't express exactly. Needs React 18+ (useId).\n`;

  const constants = usesPolygon
    ? `const PATH_D = ${JSON.stringify(result.pathD)};
const CLIP_POLYGON = ${JSON.stringify(polygon)};
const ASPECT_RATIO = ${Number.isFinite(result.aspectRatio) ? result.aspectRatio.toFixed(4) : "1"};`
    : `const PATH_D = ${JSON.stringify(result.pathD)};
const ASPECT_RATIO = ${Number.isFinite(result.aspectRatio) ? result.aspectRatio.toFixed(4) : "1"};`;

  const hookLine = usesPolygon ? "" : "  const clipId = React.useId();\n";

  const childrenBlock = usesPolygon
    ? `  if (children) {
    return (
      <div
        className={className}
        data-kerf-shape="${componentName}"
        style={{
          position: "relative",
          display: "inline-block",
          overflow: "hidden",
          width: w,
          height: h,
          aspectRatio: preserveAspect,
          clipPath: \`polygon(\${CLIP_POLYGON})\`,
          WebkitClipPath: \`polygon(\${CLIP_POLYGON})\`,
          ...style,
        }}
      >
        {children}
      </div>
    );
  }`
    : `  if (children) {
    return (
      <div
        className={className}
        data-kerf-shape="${componentName}"
        style={{
          position: "relative",
          display: "inline-block",
          overflow: "hidden",
          width: w,
          height: h,
          aspectRatio: preserveAspect,
          clipPath: \`url(#\${clipId})\`,
          WebkitClipPath: \`url(#\${clipId})\`,
          ...style,
        }}
      >
        <svg width={0} height={0} style={{ position: "absolute" }} aria-hidden focusable="false">
          <defs>
            <clipPath id={clipId} clipPathUnits="objectBoundingBox">
              <path d={PATH_D} clipRule="evenodd" />
            </clipPath>
          </defs>
        </svg>
        {children}
      </div>
    );
  }`;

  return `/**
 * Generated by Kerf from ${JSON.stringify(result.sourceFile)} — do not edit by hand.
 * Regenerate: npx kerf-shapes trace ${JSON.stringify(result.sourceFile)} --name ${componentName}
${headerNote} */
import * as React from "react";

${constants}

export interface ${componentName}Props
  extends Omit<React.SVGAttributes<SVGSVGElement>, "children"> {
  /** Uniform size (px or CSS length). Sets width and height together, preserving aspect ratio. Ignored if \`height\` is also set. */
  size?: number | string;
  width?: number | string;
  height?: number | string;
  /** Fill color when rendered as a flat shape (ignored when \`children\` is passed). */
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
  /** Pass children to clip arbitrary content (images, video, text) to this silhouette instead of filling it flat. */
  children?: React.ReactNode;
}

/**
 * ${componentName} — traced with Kerf.
 * No children: renders as a flat, filled/stroked SVG shape.
 * With children: clips whatever you pass in to this shape's silhouette.
 */
export function ${componentName}({
  size,
  width,
  height,
  fill = ${JSON.stringify(defaultFill)},
  stroke = ${strokeDefault},
  strokeWidth = ${defaultStrokeWidth},
  className,
  style,
  children,
  ...rest
}: ${componentName}Props) {
  const w = width ?? size;
  const h = height;
  const preserveAspect = h === undefined && w !== undefined ? ASPECT_RATIO : undefined;
${hookLine}
${childrenBlock}

  return (
    <svg
      viewBox="0 0 1 1"
      preserveAspectRatio="none"
      width={w}
      height={h}
      className={className}
      data-kerf-shape="${componentName}"
      style={{ aspectRatio: preserveAspect, ...style }}
      {...rest}
    >
      <path
        d={PATH_D}
        fill={fill}
        stroke={stroke}
        strokeWidth={strokeWidth}
        fillRule="evenodd"
        vectorEffect="non-scaling-stroke"
      />
    </svg>
  );
}

export default ${componentName};
`;
}

let cachedPrettier: typeof import("prettier") | null | undefined;

async function getPrettier() {
  if (cachedPrettier !== undefined) return cachedPrettier;
  try {
    cachedPrettier = await import("prettier");
  } catch {
    cachedPrettier = null;
  }
  return cachedPrettier;
}

/** Same as `generateComponentSource`, run through Prettier when it's available. */
export async function generateAndFormatComponent(
  result: TraceResult,
  opts: CodegenOptions
): Promise<string> {
  const source = generateComponentSource(result, opts);
  const prettier = await getPrettier();
  if (!prettier) return source;
  try {
    return await prettier.format(source, { parser: "babel-ts", printWidth: 100 });
  } catch {
    return source;
  }
}
